Repository voxpupuli/beaker-docker, pull requests merged in 2021-08, with the labels that each got.

#49 Implement codecov reporting
  .github/workflows/release.yml
  .github/workflows/test.yml
  Gemfile
  README.md
  beaker-docker.gemspec
  spec/spec_helper.rb
Labels: enhancement

#47 Be more aggressive about picking a connection
  lib/beaker/hypervisor/docker.rb
  spec/beaker/hypervisor/docker_spec.rb
Labels: bug

#50 Release 1.0.0
  CHANGELOG.md
  Rakefile
  lib/beaker-docker/version.rb
Labels: skip-changelog
