Repository voxpupuli/beaker-docker, pull requests merged in 2023-03, with the labels that each got.

#84 set flag for container to container communication
  .github/workflows/test.yml
  .gitignore
  .rubocop_todo.yml
  Rakefile
  lib/beaker/hypervisor/docker.rb
Labels: bug

#91 Release 1.4.0
  CHANGELOG.md
  lib/beaker-docker/version.rb
Labels: skip-changelog

#87 Add Ruby 3.1 to CI matrix
  .github/workflows/test.yml
Labels: enhancement

#93 Deal with docker_cmd being an array and remove use of =~
  .rubocop_todo.yml
  Rakefile
  lib/beaker/hypervisor/docker.rb
  spec/beaker/hypervisor/docker_spec.rb
Labels: bug

#99 Set required Ruby version to 2.4+
  beaker-docker.gemspec
Labels: enhancement

#100 Ruby 3.2 compatibility
  .github/workflows/test.yml
  Gemfile
Labels: enhancement

#101 CI: Dont fail fast
  .github/workflows/test.yml
Labels: skip-changelog

#105 Release 1.5.0
  CHANGELOG.md
  lib/beaker-docker/version.rb
Labels: skip-changelog

#109 Drop Ruby 2.4/2.5/2.6 support
  .github/workflows/test.yml
  .rubocop.yml
  .rubocop_todo.yml
  beaker-docker.gemspec
  lib/beaker/hypervisor/docker.rb
  spec/beaker/hypervisor/docker_spec.rb
Labels: backwards-incompatible

#107 Drop `beaker-rspec` dependency
  Gemfile
Labels: enhancement
